spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      properties:
        hibernate:
          enable_lazy_load_no_trans: true
          format_sql: true
        jadira:
          usertype:
            autoRegisterUserTypes: true
      generate-ddl: true
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      open-in-view: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.98.51.229:3306/jpa?characterEncoding=utf-8&useSSL=false
    username: root
    password: asusA123

